package dataAccess.Entities;
// Generated 25/05/2014 12:05:07 AM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Console generated by hbm2java
 */
public class Console  implements java.io.Serializable {


     private int idConsole;
     private String company;
     private Set<Product> products = new HashSet<Product>(0);

    public Console() {
    }

	
    public Console(int idConsole, String company) {
        this.idConsole = idConsole;
        this.company = company;
    }
    public Console(int idConsole, String company, Set<Product> products) {
       this.idConsole = idConsole;
       this.company = company;
       this.products = products;
    }
   
    public int getIdConsole() {
        return this.idConsole;
    }
    
    public void setIdConsole(int idConsole) {
        this.idConsole = idConsole;
    }
    public String getCompany() {
        return this.company;
    }
    
    public void setCompany(String company) {
        this.company = company;
    }
    public Set<Product> getProducts() {
        return this.products;
    }
    
    public void setProducts(Set<Product> products) {
        this.products = products;
    }




}
