package dataAccess.Entities;

// Generated 20/05/2014 01:17:10 AM by Hibernate Tools 4.0.0

/**
 * Directionaddres generated by hbm2java
 */
public class Directionaddres implements java.io.Serializable {

	private int idDirectionAddres;
	private User user;
	private String street;
	private int number;
	private String cityWard;
	private String country;
	private String state;
	private String zipCode;

	public Directionaddres() {
	}

	public Directionaddres(int idDirectionAddres, User user, String street,
			int number, String cityWard, String country, String state,
			String zipCode) {
		this.idDirectionAddres = idDirectionAddres;
		this.user = user;
		this.street = street;
		this.number = number;
		this.cityWard = cityWard;
		this.country = country;
		this.state = state;
		this.zipCode = zipCode;
	}

	public int getIdDirectionAddres() {
		return this.idDirectionAddres;
	}

	public void setIdDirectionAddres(int idDirectionAddres) {
		this.idDirectionAddres = idDirectionAddres;
	}

	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public String getStreet() {
		return this.street;
	}

	public void setStreet(String street) {
		this.street = street;
	}

	public int getNumber() {
		return this.number;
	}

	public void setNumber(int number) {
		this.number = number;
	}

	public String getCityWard() {
		return this.cityWard;
	}

	public void setCityWard(String cityWard) {
		this.cityWard = cityWard;
	}

	public String getCountry() {
		return this.country;
	}

	public void setCountry(String country) {
		this.country = country;
	}

	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}

	public String getZipCode() {
		return this.zipCode;
	}

	public void setZipCode(String zipCode) {
		this.zipCode = zipCode;
	}

}
