package dataAccess.Entities;

// Generated 20/05/2014 01:17:10 AM by Hibernate Tools 4.0.0

import java.util.Date;

/**
 * Payment generated by hbm2java
 */
public class Payment implements java.io.Serializable {

	private int idPayment;
	private User user;
	private boolean type;
	private int noCard;
	private Date expDate;
	private String ownerName;
	private int controlCode;
	private int zipCode;

	public Payment() {
	}

	public Payment(int idPayment, User user, boolean type, int noCard,
			Date expDate, String ownerName, int controlCode, int zipCode) {
		this.idPayment = idPayment;
		this.user = user;
		this.type = type;
		this.noCard = noCard;
		this.expDate = expDate;
		this.ownerName = ownerName;
		this.controlCode = controlCode;
		this.zipCode = zipCode;
	}

	public int getIdPayment() {
		return this.idPayment;
	}

	public void setIdPayment(int idPayment) {
		this.idPayment = idPayment;
	}

	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public boolean isType() {
		return this.type;
	}

	public void setType(boolean type) {
		this.type = type;
	}

	public int getNoCard() {
		return this.noCard;
	}

	public void setNoCard(int noCard) {
		this.noCard = noCard;
	}

	public Date getExpDate() {
		return this.expDate;
	}

	public void setExpDate(Date expDate) {
		this.expDate = expDate;
	}

	public String getOwnerName() {
		return this.ownerName;
	}

	public void setOwnerName(String ownerName) {
		this.ownerName = ownerName;
	}

	public int getControlCode() {
		return this.controlCode;
	}

	public void setControlCode(int controlCode) {
		this.controlCode = controlCode;
	}

	public int getZipCode() {
		return this.zipCode;
	}

	public void setZipCode(int zipCode) {
		this.zipCode = zipCode;
	}

}
