package dataAccess.Entities;

// Generated 20/05/2014 01:17:10 AM by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Product generated by hbm2java
 */
public class Product implements java.io.Serializable {

	private int idProduct;
	private String name;
	private String desc;
	private float prize;
	private int stars;
	private int quantity;
	private Date creationDate;
	private String image;
	private Set wishlists = new HashSet(0);
	private Set shoppingcarhistories = new HashSet(0);
	private Set consoles = new HashSet(0);

	public Product() {
	}

	public Product(int idProduct, String name, String desc, float prize,
			int stars, int quantity, Date creationDate, String image) {
		this.idProduct = idProduct;
		this.name = name;
		this.desc = desc;
		this.prize = prize;
		this.stars = stars;
		this.quantity = quantity;
		this.creationDate = creationDate;
		this.image = image;
	}

	public Product(int idProduct, String name, String desc, float prize,
			int stars, int quantity, Date creationDate, String image, Set wishlists,
			Set shoppingcarhistories, Set consoles) {
		this.idProduct = idProduct;
		this.name = name;
		this.desc = desc;
		this.prize = prize;
		this.stars = stars;
		this.quantity = quantity;
		this.creationDate = creationDate;
		this.image = image;
		this.wishlists = wishlists;
		this.shoppingcarhistories = shoppingcarhistories;
		this.consoles = consoles;
	}

	public int getIdProduct() {
		return this.idProduct;
	}

	public void setIdProduct(int idProduct) {
		this.idProduct = idProduct;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getDesc() {
		return this.desc;
	}

	public void setDesc(String desc) {
		this.desc = desc;
	}

	public float getPrize() {
		return this.prize;
	}

	public void setPrize(float prize) {
		this.prize = prize;
	}

	public int getStars() {
		return this.stars;
	}

	public void setStars(int stars) {
		this.stars = stars;
	}

	public int getQuantity() {
		return this.quantity;
	}

	public void setQuantity(int quantity) {
		this.quantity = quantity;
	}

	public Date getCreationDate() {
		return this.creationDate;
	}

	public void setCreationDate(Date creationDate) {
		this.creationDate = creationDate;
	}
	
	public String getImage(){
		return this.image;
	}
	
	public void setImage(String image){
		this.image=image;
	}

	public Set getWishlists() {
		return this.wishlists;
	}

	public void setWishlists(Set wishlists) {
		this.wishlists = wishlists;
	}

	public Set getShoppingcarhistories() {
		return this.shoppingcarhistories;
	}

	public void setShoppingcarhistories(Set shoppingcarhistories) {
		this.shoppingcarhistories = shoppingcarhistories;
	}

	public Set getConsoles() {
		return this.consoles;
	}

	public void setConsoles(Set consoles) {
		this.consoles = consoles;
	}

}
