package dataAccess.Entities;

// Generated 20/05/2014 01:17:10 AM by Hibernate Tools 4.0.0

/**
 * UserId generated by hbm2java
 */
public class UserId implements java.io.Serializable {

	private int idUser;
	private boolean type;

	public UserId() {
	}

	public UserId(int idUser, boolean type) {
		this.idUser = idUser;
		this.type = type;
	}

	public int getIdUser() {
		return this.idUser;
	}

	public void setIdUser(int idUser) {
		this.idUser = idUser;
	}

	public boolean isType() {
		return this.type;
	}

	public void setType(boolean type) {
		this.type = type;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof UserId))
			return false;
		UserId castOther = (UserId) other;

		return (this.getIdUser() == castOther.getIdUser())
				&& (this.isType() == castOther.isType());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdUser();
		result = 37 * result + (this.isType() ? 1 : 0);
		return result;
	}

}
