package dataAccess.Entities;

// Generated 20/05/2014 01:17:10 AM by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * User generated by hbm2java
 */
public class User implements java.io.Serializable {

	private UserId id;
	private String userName;
	private String passWord;
	private String name;
	private String lastName;
	private String email;
	private Date birthDate;
	private Set payments = new HashSet(0);
	private Set wishlists = new HashSet(0);
	private Set directionaddreses = new HashSet(0);
	private Set shoppingcarhistories = new HashSet(0);

	public User(){
		
	}
	
	public User(UserId id, String userName, String passWord, String name,
			String lastName, String email, Date birthDate) {
		this.id = id;
		this.userName = userName;
		this.passWord = passWord;
		this.name = name;
		this.lastName = lastName;
		this.email = email;
		this.birthDate = birthDate;
	}
	
	public User(int id, boolean type, String userName, String passWord, String name,
			String lastName, String email, Date birthDate) {
		UserId idu=new UserId(id, type);
		this.id = idu;
		this.userName = userName;
		this.passWord = passWord;
		this.name = name;
		this.lastName = lastName;
		this.email = email;
		this.birthDate = birthDate;
	}

	public User(int id, boolean type, String userName, String passWord, String name,
			String lastName, String email, Date birthDate, Set payments,
			Set wishlists, Set directionaddreses, Set shoppingcarhistories) {
		UserId idu=new UserId(id, type);
		this.id = idu;
		this.userName = userName;
		this.passWord = passWord;
		this.name = name;
		this.lastName = lastName;
		this.email = email;
		this.birthDate = birthDate;
		this.payments = payments;
		this.wishlists = wishlists;
		this.directionaddreses = directionaddreses;
		this.shoppingcarhistories = shoppingcarhistories;
	}

	public UserId getId() {
		return this.id;
	}

	public void setId(UserId id) {
		this.id = id;
	}

	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	public String getPassWord() {
		return this.passWord;
	}

	public void setPassWord(String passWord) {
		this.passWord = passWord;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getLastName() {
		return this.lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public Date getBirthDate() {
		return this.birthDate;
	}

	public void setBirthDate(Date birthDate) {
		this.birthDate = birthDate;
	}

	public Set getPayments() {
		return this.payments;
	}

	public void setPayments(Set payments) {
		this.payments = payments;
	}

	public Set getWishlists() {
		return this.wishlists;
	}

	public void setWishlists(Set wishlists) {
		this.wishlists = wishlists;
	}

	public Set getDirectionaddreses() {
		return this.directionaddreses;
	}

	public void setDirectionaddreses(Set directionaddreses) {
		this.directionaddreses = directionaddreses;
	}

	public Set getShoppingcarhistories() {
		return this.shoppingcarhistories;
	}

	public void setShoppingcarhistories(Set shoppingcarhistories) {
		this.shoppingcarhistories = shoppingcarhistories;
	}

}
