package dataAccess.Entities;

// Generated 20/05/2014 01:17:10 AM by Hibernate Tools 4.0.0

/**
 * WishlistId generated by hbm2java
 */
public class WishlistId implements java.io.Serializable {

	private int userIdUser;
	private boolean userType;
	private int productIdProduct;

	public WishlistId() {
	}

	public WishlistId(int userIdUser, boolean userType, int productIdProduct) {
		this.userIdUser = userIdUser;
		this.userType = userType;
		this.productIdProduct = productIdProduct;
	}

	public int getUserIdUser() {
		return this.userIdUser;
	}

	public void setUserIdUser(int userIdUser) {
		this.userIdUser = userIdUser;
	}

	public boolean isUserType() {
		return this.userType;
	}

	public void setUserType(boolean userType) {
		this.userType = userType;
	}

	public int getProductIdProduct() {
		return this.productIdProduct;
	}

	public void setProductIdProduct(int productIdProduct) {
		this.productIdProduct = productIdProduct;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof WishlistId))
			return false;
		WishlistId castOther = (WishlistId) other;

		return (this.getUserIdUser() == castOther.getUserIdUser())
				&& (this.isUserType() == castOther.isUserType())
				&& (this.getProductIdProduct() == castOther
						.getProductIdProduct());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getUserIdUser();
		result = 37 * result + (this.isUserType() ? 1 : 0);
		result = 37 * result + this.getProductIdProduct();
		return result;
	}

}
